#
# Copyright 2011-2019 B2i Healthcare Pte Ltd, http://b2i.sg
#

# necessary to connect one user to the system otherwise Snow Owl startup fails
systemUser: true

identity:
  providers:
    - file:
        name: users
#   - ldap:
#        uri: <ldap_uri>
#        baseDn: dc=snowowl,dc=b2international,dc=com
#        rootDn: cn=admin,dc=snowowl,dc=b2international,dc=com
#        rootDnPassword: <adminpwd>
#        userIdProperty: uid
#        usePool: false

monitoring:
  enabled: true

