#
# Copyright 2011-2017 B2i Healthcare Pte Ltd, http://b2i.sg
#

# Default identity provider is `file`.
# You can specify users in the `configuration/users` file in the form of <username>:<password>, where the password is BCrypt encrypted hash of the password
# The default user is `snowowl` with the password of `snowowl`
# NOTE: it is recommended to change the default username/password in production environments
# Also Snow Owl supports ldap identity provider see the example below on how to configure it
identity:
  providers:
    - file:
        name: users
#    - ldap:
#        uri: <ldap_uri>
#        baseDn: dc=snowowl,dc=b2international,dc=com
#        rootDn: cn=admin,dc=snowowl,dc=b2international,dc=com
#        rootDnPassword: <adminpwd>
#        userIdProperty: uid
#        usePool: false

repository:
  host: 0.0.0.0
  port: 2036

  database:
    type: b2i_mysql
    datasource: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    driver: com.mysql.jdbc.Driver
    scheme: jdbc:mysql://
    location: localhost:3306/
    settings: ?useServerPrepStmts=true&useCursorFetch=true
    
    # Default username and password to access a local MySQL installation
    # NOTE: changing the default username/password is recommended for production environments
    username: snowowl
    password: snowowl
    
# Request execution metrics (response-time, detailed information about transactions, etc.)
metrics:
  enabled: true

# reviewManager:
  # Minutes to keep reviews in CURRENT state persisted in the index (default 15 minutes)
  # keepCurrentMins: 15
  # Minutes to keep reviews in others states persisted (default 5 minutes)
  # keepOtherMins: 5
