#
# Copyright 2011-2019 B2i Healthcare Pte Ltd, http://b2i.sg
#

# Redirects configuration directory to a random directory under OSGI installation directory
configurationDirectory: testing/rest/configuration

# Redirects resources directory to have a clean H2 content
resourceDirectory: testing/rest/resources

# necessary to connect one user to the system otherwise Snow Owl startup fails
systemUser: true

identity:
  providers:
    - file:
        name: users
  
snomed:
  # Disable concrete domains, we are going to import the required concepts to an extension
  concreteDomainSupport: false
  maxReasonerCount: 1

# cis:
#  strategy : CIS
#  cisBaseUrl: http://localhost:9090/snowowl/cis/
#  cisUserName: snowowl
#  cisPassword: snowowl
  
metrics:
  enabled: true
  
repository:
  deploymentId: api-test
  
  index:
    socketTimeout: 60000

